const {chromium}=require('/Users/dittes/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///Users/dittes/Documents/Animal%20Attack/index.html?debug',{waitUntil:'load'});await page.waitForFunction(()=>window.AnimalAttack?.state,{timeout:60000});await page.waitForTimeout(1200);
await page.screenshot({path:'.work/desktop.png',fullPage:true});const metrics=[];
for(const [width,height] of [[320,640],[360,640],[375,812],[390,844],[414,896],[768,1024]]){await page.setViewportSize({width,height});await page.waitForTimeout(150);metrics.push(await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,footer:document.querySelector('.footer-note').getBoundingClientRect().bottom,targets:[...document.querySelectorAll('button:not(:disabled)')].filter(b=>b.getBoundingClientRect().width>0).map(b=>({id:b.id,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})).filter(b=>b.w<47||b.h<47)})));if(width===390||width===360)await page.screenshot({path:`.work/mobile-${width}.png`,fullPage:true});}
console.log('LAYOUT',JSON.stringify(metrics));
await page.setViewportSize({width:390,height:844});const initial=await page.evaluate(()=>JSON.stringify(AnimalAttack.state));await page.locator('#hint').click();assert(await page.locator('.nest.safe').count());await page.locator('.nest.safe').click({force:true});assert(await page.evaluate(()=>AnimalAttack.busy));await page.waitForTimeout(650);await page.screenshot({path:'.work/action.png'});await page.waitForFunction(()=>!AnimalAttack.busy,{timeout:30000});await page.keyboard.press('u');assert.equal(await page.evaluate(()=>JSON.stringify(AnimalAttack.state)),initial,'Undo should restore exact state');
await page.locator('#extra').click();assert.equal(await page.evaluate(()=>AnimalAttack.state.active.length),6);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>AnimalAttack.state.active.length),5);
await page.locator('#settings').click();await page.locator('[data-setting="language"]').click();assert.equal(await page.locator('html').getAttribute('lang'),'de');await page.screenshot({path:'.work/settings-de.png'});console.log('GERMAN',await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,footer:document.querySelector('.footer-note').getBoundingClientRect().bottom})));await page.locator('[data-setting="language"]').click();await page.locator('[data-action="close"]').click();
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.AnimalAttack?.state,{timeout:60000});const route=await page.evaluate(()=>AnimalAttack.solve(AnimalAttack.state).route);for(const col of route){await page.keyboard.press(String(col+1));await page.waitForFunction(()=>!AnimalAttack.busy,{timeout:10000});}assert.equal(await page.evaluate(()=>AnimalAttack.state.status),'win');await page.waitForTimeout(800);assert(await page.locator('#modal').isVisible());await page.screenshot({path:'.work/win.png'});console.log('WIN',await page.evaluate(()=>({state:AnimalAttack.state.status,coins:document.querySelector('#coins').textContent,debug:document.querySelector('#debug').textContent})));
await page.locator('[data-action="next"]').click();assert.equal(await page.evaluate(()=>AnimalAttack.state.round),0);await page.locator('#map').click();assert.equal(await page.locator('.map-level:not(:disabled)').count(),2);
assert.deepEqual(errors,[]);console.log('BROWSER PASS: file:// startup, no runtime errors, round input lock, safe hint, exact undo, extra slot and undo, DE/EN settings, keyboard win, coins, next level and map unlocking.');fs.writeFileSync('.work/browser-results.json',JSON.stringify({errors,metrics},null,2));for(const n of [1,2,3,4,5]){await page.goto('file:///Users/dittes/Documents/Animal%20Attack/milestones/M'+n+'.html');await page.waitForFunction(()=>window.AnimalAttack?.state,{timeout:60000});assert.equal(await page.evaluate(()=>AnimalAttack.levels.length),n<3?3:24);console.log('M'+n+' standalone startup passed');}await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
